db.url=jdbc:mysql://localhost:3306/acervo?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
db.usuario=root
db.senha=Fatec20252

Connection conexao = DriverManager.getConnection(url, usuario, senha);
 